/**:
    ros__parameters:
      video_device: "/dev/video0"
      framerate: 5.0
      io_method: "mmap"
      frame_id: "camera"
      pixel_format: "raw_mjpeg"
      av_device_format: "YUV422P"
      image_width: 320
      image_height: 240
      camera_name: "tools_camera"
      camera_info_url: "package://usb_cam/config/camera_info.yaml"
      brightness: -1
      contrast: -1
      saturation: -1
      sharpness: -1
      gain: -1
